version: "3.8"
services:
  php-api:
    build: ./backend-php
    container_name: php-service
    ports:
      - "8080:80"
    env_file:
      - .env
    depends_on:
      - db

  node-auth:
    build: ./backend-node
    container_name: node-service
    ports:
      - "${PORT}:3000"
    environment:
      JWT_SECRET: ${JWT_SECRET}
    env_file:
      - .env
    volumes:
      - ./backend-node/users.json:/app/users.json

  db:
    image: mysql:8
    container_name: mysql-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
