version: "3.8"
services:
  php-api:
    build: ./backend-php  
    container_name: php-service
    ports:
    - "8080:80"
    depends_on:
    - db
    env_file:
    - .env
    volumes:
      - ./backend-php/cors.conf:/etc/apache2/conf-available/cors.conf


  node-auth:
    build: ./backend-node
    container_name: node-service
    ports:
      - "3000:3000"
    volumes:
      - ./backend-node/users.json:/app/users.json

  db:
    image: mysql:8
    container_name: mysql-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: recettes
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"  
    volumes:
      - db_data:/var/lib/mysql
  frontend:
    build: ./frontend
    container_name: frontend-service
    ports:
      - "8081:80"
    depends_on:
      - php-api
      - node-auth

volumes:
  db_data:
